// This file was automatically generated by impls.rs.tera. Do not edit

use crate::{
    model::common::{Ident, Type},
    resolver::ConcreteType,
    signature::ImplDetails,
};

pub fn add_impl_details(
    details: &mut ImplDetails,
    trt: &Ident,
    implementee: ConcreteType,
    associated_ty: Vec<&Type>,
) {
    match (implementee, associated_ty.as_slice()) {
        (ConcreteType::Float, [Type::Concrete(ConcreteType::Float)])
            if *trt == Ident::new("Add") =>
        {
            add_float_float(details);
        }
        (ConcreteType::Float, [Type::Concrete(ConcreteType::Int)]) if *trt == Ident::new("Add") => {
            add_float_int(details);
        }
        (ConcreteType::Int, [Type::Concrete(ConcreteType::Int)]) if *trt == Ident::new("Add") => {
            add_int_int(details);
        }
        (ConcreteType::Float, [Type::Concrete(ConcreteType::Float)])
            if *trt == Ident::new("Subtract") =>
        {
            subtract_float_float(details);
        }
        (ConcreteType::Float, [Type::Concrete(ConcreteType::Int)])
            if *trt == Ident::new("Subtract") =>
        {
            subtract_float_int(details);
        }
        (ConcreteType::Int, [Type::Concrete(ConcreteType::Int)])
            if *trt == Ident::new("Subtract") =>
        {
            subtract_int_int(details);
        }
        _ => {}
    }
}

fn add_float_float(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}
fn add_float_int(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}
fn add_int_int(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}

fn subtract_float_float(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}
fn subtract_float_int(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}
fn subtract_int_int(details: &mut ImplDetails) {
    *details = ImplDetails::Direct { code: vec![6] };
}
