
// This file is automatically generated. DO NOT EDIT. To update run `cargo run gen-std` in tools

use puffin_source::id::{Arena, InFile, ID};
use puffin_vfs::FileID;
use puffin_ast::ast::AstMap;

use crate::{model::{Trait, TraitSource, common::{Ident, Type}, Pattern}, signature::{TraitSignature, FunctionSignature}};

pub fn std_traits() -> Arena<Trait> {
    let mut std = Arena::new();
    std.alloc(add_trait());
    std.alloc(subtract_trait());
    std
}

fn add_trait() -> Trait {
    let mut pat_alloc = Arena::new();
    let mut ty_alloc = Arena::new();
    let ty1 = ty_alloc.alloc(Type::Unknown);
    let ty2 = ty_alloc.alloc(Type::Unknown);
    let a = pat_alloc.alloc(Pattern::Ident{ ident: Ident::new("a"), ty: ty1 });
    let b = pat_alloc.alloc(Pattern::Ident{ ident: Ident::new("b"), ty: ty2 });
}

fn subtract_trait() -> Trait {
    let mut pat_alloc = Arena::new();
    let mut ty_alloc = Arena::new();
    let ty1 = ty_alloc.alloc(Type::Unknown);
    let ty2 = ty_alloc.alloc(Type::Unknown);
    let a = pat_alloc.alloc(Pattern::Ident{ ident: Ident::new("a"), ty: ty1 });
    let b = pat_alloc.alloc(Pattern::Ident{ ident: Ident::new("b"), ty: ty2 });
    let sig = TraitSignature{
        name: Ident::new("Subtract"),
        types: 2
    };
    let src = TraitSource{
        ast_id: InFile::new(ID::from(7), FileID(0)),
        pat_alloc,
        ty_alloc,
        pat_map: AstMap::new(),
        ty_map: AstMap::new(),
        signatures: vec![FunctionSignature{
            param: 2,
            name: Ident::new("subtract"),
            rtrn: true,
        }]
    };
    Trait {
        signature: sig,
        source: src,
    }
}
